/**
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MdsFormProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * MdsFormPanel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-07-23T19:08:31.348+02:00")
public class MdsFormPanel   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("styleName")
  private String styleName = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("layout")
  private String layout = null;

  @SerializedName("onCreate")
  private Boolean onCreate = false;

  @SerializedName("onUpdate")
  private Boolean onUpdate = false;

  @SerializedName("multiUpload")
  private Boolean multiUpload = false;

  @SerializedName("order")
  private String order = null;

  @SerializedName("properties")
  private List<MdsFormProperty> properties = new ArrayList<MdsFormProperty>();

  public MdsFormPanel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MdsFormPanel styleName(String styleName) {
    this.styleName = styleName;
    return this;
  }

   /**
   * Get styleName
   * @return styleName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getStyleName() {
    return styleName;
  }

  public void setStyleName(String styleName) {
    this.styleName = styleName;
  }

  public MdsFormPanel label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public MdsFormPanel layout(String layout) {
    this.layout = layout;
    return this;
  }

   /**
   * Get layout
   * @return layout
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLayout() {
    return layout;
  }

  public void setLayout(String layout) {
    this.layout = layout;
  }

  public MdsFormPanel onCreate(Boolean onCreate) {
    this.onCreate = onCreate;
    return this;
  }

   /**
   * Get onCreate
   * @return onCreate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getOnCreate() {
    return onCreate;
  }

  public void setOnCreate(Boolean onCreate) {
    this.onCreate = onCreate;
  }

  public MdsFormPanel onUpdate(Boolean onUpdate) {
    this.onUpdate = onUpdate;
    return this;
  }

   /**
   * Get onUpdate
   * @return onUpdate
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getOnUpdate() {
    return onUpdate;
  }

  public void setOnUpdate(Boolean onUpdate) {
    this.onUpdate = onUpdate;
  }

  public MdsFormPanel multiUpload(Boolean multiUpload) {
    this.multiUpload = multiUpload;
    return this;
  }

   /**
   * Get multiUpload
   * @return multiUpload
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getMultiUpload() {
    return multiUpload;
  }

  public void setMultiUpload(Boolean multiUpload) {
    this.multiUpload = multiUpload;
  }

  public MdsFormPanel order(String order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getOrder() {
    return order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public MdsFormPanel properties(List<MdsFormProperty> properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<MdsFormProperty> getProperties() {
    return properties;
  }

  public void setProperties(List<MdsFormProperty> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MdsFormPanel mdsFormPanel = (MdsFormPanel) o;
    return Objects.equals(this.name, mdsFormPanel.name) &&
        Objects.equals(this.styleName, mdsFormPanel.styleName) &&
        Objects.equals(this.label, mdsFormPanel.label) &&
        Objects.equals(this.layout, mdsFormPanel.layout) &&
        Objects.equals(this.onCreate, mdsFormPanel.onCreate) &&
        Objects.equals(this.onUpdate, mdsFormPanel.onUpdate) &&
        Objects.equals(this.multiUpload, mdsFormPanel.multiUpload) &&
        Objects.equals(this.order, mdsFormPanel.order) &&
        Objects.equals(this.properties, mdsFormPanel.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, styleName, label, layout, onCreate, onUpdate, multiUpload, order, properties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MdsFormPanel {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    styleName: ").append(toIndentedString(styleName)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    layout: ").append(toIndentedString(layout)).append("\n");
    sb.append("    onCreate: ").append(toIndentedString(onCreate)).append("\n");
    sb.append("    onUpdate: ").append(toIndentedString(onUpdate)).append("\n");
    sb.append("    multiUpload: ").append(toIndentedString(multiUpload)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

