/**
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.NodeProperty;
import io.swagger.client.model.NodeVersionRef;
import io.swagger.client.model.Person;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * NodeVersion
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-07-23T18:46:07.581+02:00")
public class NodeVersion   {
  @SerializedName("properties")
  private List<NodeProperty> properties = new ArrayList<NodeProperty>();

  @SerializedName("version")
  private NodeVersionRef version = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("modifiedAt")
  private DateTime modifiedAt = null;

  @SerializedName("modifiedBy")
  private Person modifiedBy = null;

  @SerializedName("contentUrl")
  private String contentUrl = null;

  public NodeVersion properties(List<NodeProperty> properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<NodeProperty> getProperties() {
    return properties;
  }

  public void setProperties(List<NodeProperty> properties) {
    this.properties = properties;
  }

  public NodeVersion version(NodeVersionRef version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public NodeVersionRef getVersion() {
    return version;
  }

  public void setVersion(NodeVersionRef version) {
    this.version = version;
  }

  public NodeVersion comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public NodeVersion modifiedAt(DateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(DateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }

  public NodeVersion modifiedBy(Person modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Person getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Person modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public NodeVersion contentUrl(String contentUrl) {
    this.contentUrl = contentUrl;
    return this;
  }

   /**
   * Get contentUrl
   * @return contentUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContentUrl() {
    return contentUrl;
  }

  public void setContentUrl(String contentUrl) {
    this.contentUrl = contentUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeVersion nodeVersion = (NodeVersion) o;
    return Objects.equals(this.properties, nodeVersion.properties) &&
        Objects.equals(this.version, nodeVersion.version) &&
        Objects.equals(this.comment, nodeVersion.comment) &&
        Objects.equals(this.modifiedAt, nodeVersion.modifiedAt) &&
        Objects.equals(this.modifiedBy, nodeVersion.modifiedBy) &&
        Objects.equals(this.contentUrl, nodeVersion.contentUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties, version, comment, modifiedAt, modifiedBy, contentUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeVersion {\n");
    
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    contentUrl: ").append(toIndentedString(contentUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

