/**
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ErrorResponse;
import io.swagger.client.model.MdsEntry;
import io.swagger.client.model.MdsEntries;
import io.swagger.client.model.ValueParameters;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MDSVApi
 */
public class MDSVApiTest {

    private final MDSVApi api = new MDSVApi();

    
    /**
     * Get metadata set.
     *
     * Get metadata set.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMetadataSetTest() throws ApiException {
        String repository = null;
        String metadataset = null;
        // MdsEntry response = api.getMetadataSet(repository, metadataset);

        // TODO: test validations
    }
    
    /**
     * Get metadata sets of repository.
     *
     * Get metadata sets of repository.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMetadataSetsTest() throws ApiException {
        String repository = null;
        // MdsEntries response = api.getMetadataSets(repository);

        // TODO: test validations
    }
    
    /**
     * Get values.
     *
     * Get values.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getValuesTest() throws ApiException {
        String repository = null;
        String metadataset = null;
        ValueParameters body = null;
        // MdsEntry response = api.getValues(repository, metadataset, body);

        // TODO: test validations
    }
    
}
