/**
 * edu-sharing Repository REST API
 * The public restful API of the edu-sharing repository.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Usages;
import io.swagger.client.model.ErrorResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for USAGEVApi
 */
public class USAGEVApiTest {

    private final USAGEVApi api = new USAGEVApi();

    
    /**
     * Get all usages of an application.
     *
     * Get all usages of an application.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsagesTest() throws ApiException {
        String appId = null;
        // Usages response = api.getUsages(appId);

        // TODO: test validations
    }
    
    /**
     * Get all usages of an course.
     *
     * Get all usages of an course.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsagesByCourseTest() throws ApiException {
        String appId = null;
        String courseId = null;
        // Usages response = api.getUsagesByCourse(appId, courseId);

        // TODO: test validations
    }
    
    /**
     * Get all usages of an node.
     *
     * Get all usages of an node.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsagesByNodeTest() throws ApiException {
        String nodeId = null;
        // Usages response = api.getUsagesByNode(nodeId);

        // TODO: test validations
    }
    
}
